// REDUX ACTION TYPES
export const ADD_LEAVE_SUCCESS = "ADD_LEAVE_SUCCESS";
export const ADD_LEAVE_FAILURE = "ADD_LEAVE_FAILURE";

export const GET_LEAVES_BY_EMPLOYEE_ID_SUCCESS =
  "GET_LEAVES_BY_EMPLOYEE_ID_SUCCESS";
export const GET_LEAVES_BY_EMPLOYEE_ID_FAILURE =
  "GET_LEAVES_BY_EMPLOYEE_ID_FAILURE";

export const LEAVE_LOADING = "LEAVE_LOADING";
